### ISSUE TITLE
Ckeditor5 v11 compatibility

### ISSUE THREAD

**Issue by joachimdoerr** [mjadobson/ckeditor5-super-sub#1]
Hello, thanks for your plugin! It is great and helpful! But in the new ckeditor5 v11  we get problems with the dependency versions all dependencies there are to old cause the editor to display incorrectly. 

Take a look at this issue: https://github.com/ckeditor/ckeditor5/issues/1175

**Comment by mjadobson** [comment]
Should be fixed by #2
